### ISSUE TITLE
JSON syntax error to API server causes homebridge to crash

### ISSUE THREAD

**Issue by timwitty** [lukasroegner/homebridge-sonos-multiroom#12]
[2/9/2021, 8:09:15 PM] SyntaxError: Unexpected token x in JSON at position 27
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sonos-multiroom/src/sonos-api.js:68:33)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2/9/2021, 8:09:15 PM] Got SIGTERM, shutting down Homebridge...

I sent something like the following (without the quotes surrounding the value):
{
"current-track-uri": x-<rest of uri>
}

**Comment by lukasroegner** [comment]
Fixed in 0.5.1.
