### ISSUE TITLE
Address Conflict

### ISSUE THREAD

**Issue by ikolsteren** [lukasroegner/homebridge-sonos-multiroom#4]
New install and having a conflict with port 4000
If I do not define any zones then works
As soon as define 1 or all the speakers I get this - I tired a new install as well to avoid and conflict as well

[4/3/2020, 5:08:02 PM] Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at Server.listen (net.js:1445:7)
    at SonosListener.startListener (/homebridge/node_modules/homebridge-sonos-multiroom/node_modules/sonos/lib/events/adv-listener.js:66:25)
    at /homebridge/node_modules/homebridge-sonos-multiroom/node_modules/sonos/lib/events/adv-listener.js:100:12
    at new Promise (<anonymous>)
    at SonosListener.subscribeTo (/homebridge/node_modules/homebridge-sonos-multiroom/node_modules/sonos/lib/events/adv-listener.js:99:12)
    at Sonos.implicitListen (/homebridge/node_modules/homebridge-sonos-multiroom/node_modules/sonos/lib/sonos.js:70:21)
    at Sonos.emit (events.js:311:20)
    at _addListener (events.js:354:14)

**Comment by ikolsteren** [comment]
Moved to a Ubuntu VM and working fine
Working on making API work now
